steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile
      - --target
      - api
      - -t
      - europe-west3-docker.pkg.dev/$PROJECT_ID/recsys/recsys-api:latest
      - .
images:
  - europe-west3-docker.pkg.dev/$PROJECT_ID/recsys/recsys-api:latest