"""create users movies ratings

Revision ID: de48eeb5924c
Revises:
Create Date: 2026-01-19 18:25:11.406737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "de48eeb5924c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("genres", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("movie_id"),
    )
    op.create_index(op.f("ix_movies_movie_id"), "movies", ["movie_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("gender", sa.String(length=1), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("occupation", sa.Integer(), nullable=True),
        sa.Column("zip", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=False)
    op.create_table(
        "ratings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5", name="ck_ratings_rating_range"
        ),
        sa.ForeignKeyConstraint(["movie_id"], ["movies.movie_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "movie_id"),
    )
    op.create_index("ix_ratings_movie_id", "ratings", ["movie_id"], unique=False)
    op.create_index("ix_ratings_user_id", "ratings", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ratings_user_id", table_name="ratings")
    op.drop_index("ix_ratings_movie_id", table_name="ratings")
    op.drop_table("ratings")
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_movies_movie_id"), table_name="movies")
    op.drop_table("movies")
    # ### end Alembic commands ###
